# This is a basic workflow to help you get started with Actions

name: Create-Wiki

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update docfx.json
        run: echo "`jq '.build.globalMetadata._appFooter="Update $GITHUB_WORKFLOW#$GITHUB_RUN_NUMBER"' wiki/docfx.json`" > wiki/docfx.json
      - name: read docfx.json
        run: cat wiki/docfx.json

      - uses: nikeee/docfx-action@v1.0.0
        name: Build Documentation
        with:
          args: wiki/docfx.json

      # Publish generated site using GitHub Pages
      - uses: maxheld83/ghpages@master
        name: Publish Documentation on GitHub Pages
        env:
          BUILD_DIR: wiki/_site # docfx's default output directory is _site
          GH_PAT: ${{ secrets.GH_WIKI }} # See https://github.com/maxheld83/ghpages
